# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Push and Pull Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: osmin625
  IMAGE_NAME: hrb_server
  IMAGE_TAG: latest
  DOCKERFILE_PATH: .
  CONTAINER_NAME: backserv

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG $DOCKERFILE_PATH --push
      -
        name: executing docker pull and run commands with remote ssh using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          envs: DOCKER_USERNAME,IMAGE_NAME,IMAGE_TAG,CONTAINER_NAME
          script: |
              docker pull $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
              docker rm -f $CONTAINER_NAME
              docker rmi $(docker images -f "dangling=true" -q)
              docker run --env-file .env -d --name $CONTAINER_NAME -p 8080:8080 $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

    